version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_churn
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Only this for root password
      MYSQL_DATABASE: churn_db
      MYSQL_ROOT_HOST: "%"  # This allows connections from any host
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
